Why each package?
Package	Why we need it

transformers Loads ModernBERT, tokenizer, training utilities
torch Tensors and model executions
datasets Reads CSV/JSON datasets.
evaluate Accuracy, Precision, Recall later.
accelerate Simplifies training (works on CPU too).

In [4]:
from transformers import AutoTokenizer, AutoModel

MODEL_NAME = "answerdotai/ModernBERT-base"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModel.from_pretrained(MODEL_NAME)

config.json:   0%|          | 0.00/1.19k [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json:   0%|          | 0.00/20.8k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.13M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/694 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  599MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/134 [00:00<?, ?it/s]

[transformers] ModernBertModel LOAD REPORT from: answerdotai/ModernBERT-base
Key               | Status     |  |
------------------+------------+--+-
decoder.bias      | UNEXPECTED |  |
head.norm.weight  | UNEXPECTED |  |
head.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [5]:
tokenizer

TokenizersBackend(name_or_path='answerdotai/ModernBERT-base', vocab_size=50280, model_max_length=8192, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, added_tokens_decoder={
	0: AddedToken("|||IP_ADDRESS|||", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	1: AddedToken("<|padding|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	50254: AddedToken("                        ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50255: AddedToken("                       ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50256: AddedToken("                      ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50257: AddedToken("                     ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50258: AddedToken("                    ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50259: AddedToken("                   ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50260: AddedToken("                  ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50261: AddedToken("                 ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50262: AddedToken("                ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50263: AddedToken("               ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50264: AddedToken("              ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50265: AddedToken("             ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50266: AddedToken("            ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50267: AddedToken("           ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50268: AddedToken("          ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50269: AddedToken("         ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50270: AddedToken("        ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50271: AddedToken("       ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50272: AddedToken("      ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50273: AddedToken("     ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50274: AddedToken("    ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50275: AddedToken("   ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50276: AddedToken("  ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50277: AddedToken("|||EMAIL_ADDRESS|||", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50278: AddedToken("|||PHONE_NUMBER|||", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50279: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	50280: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	50281: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	50282: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	50283: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	50284: AddedToken("[MASK]", rstrip=False, lstrip=True, single_word=False, normalized=False, special=True),
	50285: AddedToken("[unused0]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50286: AddedToken("[unused1]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50287: AddedToken("[unused2]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50288: AddedToken("[unused3]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50289: AddedToken("[unused4]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50290: AddedToken("[unused5]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50291: AddedToken("[unused6]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50292: AddedToken("[unused7]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50293: AddedToken("[unused8]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50294: AddedToken("[unused9]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50295: AddedToken("[unused10]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50296: AddedToken("[unused11]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50297: AddedToken("[unused12]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50298: AddedToken("[unused13]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50299: AddedToken("[unused14]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50300: AddedToken("[unused15]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50301: AddedToken("[unused16]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50302: AddedToken("[unused17]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50303: AddedToken("[unused18]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50304: AddedToken("[unused19]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50305: AddedToken("[unused20]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50306: AddedToken("[unused21]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50307: AddedToken("[unused22]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50308: AddedToken("[unused23]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50309: AddedToken("[unused24]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50310: AddedToken("[unused25]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50311: AddedToken("[unused26]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50312: AddedToken("[unused27]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50313: AddedToken("[unused28]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50314: AddedToken("[unused29]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50315: AddedToken("[unused30]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50316: AddedToken("[unused31]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50317: AddedToken("[unused32]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50318: AddedToken("[unused33]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50319: AddedToken("[unused34]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50320: AddedToken("[unused35]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50321: AddedToken("[unused36]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50322: AddedToken("[unused37]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50323: AddedToken("[unused38]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50324: AddedToken("[unused39]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50325: AddedToken("[unused40]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50326: AddedToken("[unused41]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50327: AddedToken("[unused42]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50328: AddedToken("[unused43]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50329: AddedToken("[unused44]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50330: AddedToken("[unused45]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50331: AddedToken("[unused46]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50332: AddedToken("[unused47]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50333: AddedToken("[unused48]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50334: AddedToken("[unused49]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50335: AddedToken("[unused50]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50336: AddedToken("[unused51]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50337: AddedToken("[unused52]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50338: AddedToken("[unused53]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50339: AddedToken("[unused54]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50340: AddedToken("[unused55]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50341: AddedToken("[unused56]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50342: AddedToken("[unused57]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50343: AddedToken("[unused58]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50344: AddedToken("[unused59]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50345: AddedToken("[unused60]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50346: AddedToken("[unused61]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50347: AddedToken("[unused62]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50348: AddedToken("[unused63]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50349: AddedToken("[unused64]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50350: AddedToken("[unused65]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50351: AddedToken("[unused66]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50352: AddedToken("[unused67]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50353: AddedToken("[unused68]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50354: AddedToken("[unused69]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50355: AddedToken("[unused70]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50356: AddedToken("[unused71]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50357: AddedToken("[unused72]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50358: AddedToken("[unused73]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50359: AddedToken("[unused74]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50360: AddedToken("[unused75]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50361: AddedToken("[unused76]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50362: AddedToken("[unused77]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50363: AddedToken("[unused78]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50364: AddedToken("[unused79]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50365: AddedToken("[unused80]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50366: AddedToken("[unused81]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50367: AddedToken("[unused82]", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
})

In [6]:
dir(tokenizer)

['SPECIAL_TOKENS_ATTRIBUTES',
 '__annotations__',
 '__bool__',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_add_bos_token',
 '_add_eos_token',
 '_add_tokens',
 '_added_tokens_decoder',
 '_added_tokens_encoder',
 '_auto_class',
 '_convert_encoding',
 '_convert_id_to_token',
 '_convert_token_to_id_with_added_voc',
 '_decode',
 '_encode_plus',
 '_eventual_warn_about_too_long_sequence',
 '_extra_special_tokens',
 '_from_pretrained',
 '_get_files_timestamps',
 '_get_padding_truncation_strategies',
 '_in_target_context_manager',
 '_pad',
 '_pad_token_type_id',
 '_patch_mistral_regex',
 '_post_init',
 '_processor_class',
 '_save_pretrained',
 '_set_model_specific_special_tokens',
 '_set_processor_class',
 '_should_update_post_processor',
 '_special_tokens_map',
 '_tokenizer',
 '_upload_modified_files',
 'add_bos_token',
 'add_eos_token',
 'add_prefix_space',
 'add_special_tokens',
 'add_tokens',
 'added_tokens_decoder',
 'added_tokens_encoder',
 'all_special_ids',
 'all_special_tokens',
 'apply_chat_template',
 'backend',
 'backend_tokenizer',
 'batch_decode',
 'can_save_slow_tokenizer',
 'chat_template',
 'clean_up_tokenization',
 'clean_up_tokenization_spaces',
 'clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output',
 'convert_added_tokens',
 'convert_ids_to_tokens',
 'convert_to_native_format',
 'convert_tokens_to_ids',
 'convert_tokens_to_string',
 'decode',
 'decoder',
 'deprecation_warnings',
 'encode',
 'encode_message_with_chat_template',
 'files_loaded',
 'from_pretrained',
 'get_added_vocab',
 'get_chat_template',
 'get_response_parser',
 'get_special_tokens_mask',
 'get_vocab',
 'init_inputs',
 'init_kwargs',
 'is_fast',
 'max_len_sentences_pair',
 'max_len_single_sentence',
 'model',
 'model_input_names',
 'model_max_length',
 'name_or_path',
 'num_special_tokens_to_add',
 'pad',
 'pad_token_type_id',
 'padding_side',
 'parse_response',
 'pretrained_vocab_files_map',
 'push_to_hub',
 'register_for_auto_class',
 'response_template',
 'save_chat_templates',
 'save_pretrained',
 'save_vocabulary',
 'set_truncation_and_padding',
 'slow_tokenizer_class',
 'special_tokens_map',
 'split_special_tokens',
 'tokenize',
 'train_new_from_iterator',
 'truncation_side',
 'update_post_processor',
 'verbose',
 'vocab',
 'vocab_files_names',
 'vocab_size']

In [11]:
print(tokenizer.vocab_size)
tokenizer.vocab_files_names

50280

{'tokenizer_file': 'tokenizer.json', 'vocab_file': 'tokenizer.model'}

In [17]:
list(tokenizer.vocab.keys())[10:]

['Ġhorse',
 'Ġafore',
 'Ġisol',
 'ĠMaurice',
 'Known',
 'Functions',
 'ĠVAL',
 'Ġreflect',
 "Ġ''",
 'Ġappointed',
 'ĠCheng',
 'services',
 'ĠComplete',
 'odenal',
 'ĠSamuel',
 'Blood',
 'ĠEEG',
 'colors',
 'Ġnodes',
 '232',
 'calendar',
 'Ġfate',
 'Ġtriang',
 'ĠTerrit',
 'Ġservant',
 'ĠLew',
 'ĠCourts',
 'ection',
 'ano',
 'oslav',
 'cluded',
 'Ġstock',
 'reliable',
 'dden',
 'urer',
 'otransfer',
 'solete',
 'Ġsober',
 'ĠWeiss',
 'Ġgu',
 'ass',
 'nego',
 'Ġclin',
 'ĠElaine',
 'Ġtextbook',
 'Ġtug',
 'ĠReed',
 'etr',
 'ÑĬÑĢ',
 'Ġauf',
 'Roger',
 'ĠPep',
 'urally',
 'âĢ¦âĢ¦âĢ¦âĢ¦',
 'hors',
 'Ġembodied',
 'Ġmetadata',
 'Ġfib',
 'eg',
 'MSCs',
 'Ġuintptr',
 'php',
 'oping',
 'ĠXL',
 'Ġjustified',
 'Ġhackers',
 'JO',
 'haust',
 'borne',
 'ORT',
 'ĠOA',
 'ĠÐºÐ¾ÑĤÐ¾ÑĢ',
 'Ġnumb',
 'Ġpoultry',
 'ENV',
 'Ken',
 'ĠÏĩ',
 'Rx',
 'ring',
 'documentclass',
 'Id',
 'Ġanalyzing',
 'VV',
 'ires',
 'Ġhabeas',
 'Ġsam',
 'ĠKingdom',
 'Ġ"</',
 '¾',
 'alleng',
 'ĠNetflix',
 'Bucket',
 'ĠMissouri',
 'SPEC',
 'ROOT',
 'doc',
 'Ġencapsulated',
 'ĠFolk',
 'bul',
 'Ġhydroph',
 '540',
 'Ġarrest',
 'ĠBrasil',
 'DCs',
 'eful',
 'Ġcompetitive',
 'Ġintegrable',
 'Ġbuy',
 'Ġviolet',
 'aceae',
 '="\'$(',
 'taire',
 'Olymp',
 'nÄĽ',
 'Ġactivated',
 'Ġthrown',
 'ĠTol',
 'ĠTs',
 'Ġbullshit',
 'function',
 'Upload',
 'erring',
 'ellen',
 'shape',
 'ĠBangkok',
 'ĠGill',
 'Ġindex',
 'thood',
 'Ġclarification',
 'Ġexponents',
 'Ġgrouped',
 'ĠTree',
 '489',
 'Ġ544',
 'worthy',
 'ĠI',
 'MH',
 'Ġcaf',
 'Ġbizarre',
 'pause',
 'Ġaccounts',
 'Ġdissected',
 'bibr',
 '}({\\',
 'Ġinsightful',
 'gpio',
 'Ġlaunched',
 'Ġestablish',
 'Ġpenetr',
 'HDL',
 'ĠEbola',
 'Ġcrore',
 'Ġtechnique',
 'warning',
 'Ġ352',
 'Mod',
 'Ġled',
 'Ġannual',
 'ĠMitchell',
 'Ġ<!',
 'rtc',
 'irling',
 'content',
 'Ġproudly',
 'ĠZel',
 "Ġ'%",
 'Activ',
 'àµ',
 'Ġrocking',
 'DECLARE',
 'çĬ¶',
 'MAC',
 'Ġhistorians',
 'Ġprojector',
 'ĠRidge',
 'amily',
 'Ġaggravated',
 'ãģŁ',
 'Secondary',
 'Ġprescribe',
 'ĠNeal',
 'ableView',
 'Ġdifferential',
 'neutral',
 'Ġ================================================================',
 'Ġweakened',
 'MARK',
 'ĠDownload',
 'hyth',
 'Ġhace',
 'Ġ1888',
 'Ġpassenger',
 'orum',
 'Ġfoi',
 'Ġelectrode',
 'tl',
 'Ġsubgroup',
 'Hal',
 '186',
 'ĠDefendants',
 'Ġliquid',
 'Ġcontingency',
 '{|',
 'Ġcolloqu',
 'big',
 'Ġbac',
 'Due',
 'toc',
 'Today',
 'oko',
 'Ġparade',
 'Ġbishop',
 'ĠImp',
 'Ġdrivers',
 'Stat',
 'ind',
 'Ġrac',
 'ÑĬ',
 'Ġuncon',
 'Ġinsure',
 'smallmatrix',
 'Ġdoi',
 'Seg',
 'iliation',
 'cester',
 '205',
 'Ġ52',
 'onomy',
 'Lee',
 'Ġmarginal',
 'AA',
 'marshal',
 'yor',
 'Ġstripping',
 'Ġinherit',
 'XP',
 'BT',
 'Ġartery',
 'hint',
 'Ġcommodity',
 'Ġinstructed',
 'adoop',
 'jection',
 'few',
 'Ġsmear',
 'Ġdrastic',
 'bos',
 'fits',
 '_{[',
 'gypt',
 'ership',
 'Ġguessing',
 'clude',
 'ĠCraft',
 '#',
 'Ġprotections',
 'jango',
 'ĠLib',
 'ĠMental',
 'ãģ«ãģª',
 'rible',
 'ĠFamilies',
 'IQR',
 'Ġfailures',
 'Ġelevation',
 '\\~',
 'mysql',
 '}^{+',
 'UTR',
 'etz',
 'Ġ1400',
 'card',
 'Ġheights',
 '2006',
 'vens',
 'Ġsymbol',
 'Ġcontractual',
 'ĠLayout',
 'Ġjustices',
 'Ġhardness',
 'Ġsuggestive',
 'Ġ%{',
 'qp',
 'Ġ})',
 'Ġ+\\',
 'andum',
 'Ġscroll',
 'Sur',
 'inner',
 'Ġcytoplasmic',
 'running',
 'Ġpolymorph',
 'orbit',
 'You',
 'blo',
 'ĊĠĠĠĠĠĠĠĠĠĠĠĠĠĠĠĠĠĠĠĠĠĠĠ',
 '547',
 'Ġteach',
 'ä¾',
 'Ġporcine',
 'Plan',
 'ĠMarines',
 'Ġethnic',
 'Ġfunction',
 'Ġsmile',
 'Ġmultipl',
 '"[',
 'Ġaccountant',
 'Ġsacred',
 'CLUDING',
 'vered',
 'Ġsulfate',
 'Ġsalvage',
 'Âª',
 'Ġslug',
 'ĠPlaces',
 'Criteria',
 '198',
 'cum',
 'ferentially',
 'Ġspy',
 'duc',
 'ambiguation',
 'Ġgorge',
 'ãģĴ',
 'ĠAdS',
 '254',
 'Ġanalyse',
 'ĠCollect',
 'YA',
 '63',
 'swers',
 'Ġsweet',
 'Ġos',
 'Ġnd',
 'Ġspider',
 'alph',
 'ĠGrove',
 'Ġdubbed',
 'ctomy',
 'Ġ500',
 'Ġneur',
 'Ġorbital',
 'ĠSeattle',
 'ī',
 'ĠEston',
 'Ġafternoon',
 'Ġcohes',
 'pires',
 'Ġobserv',
 'Ġsurvivor',
 'Ġantiviral',
 'ĠFirefox',
 'Ġspl',
 'ĠIbid',
 'dead',
 'Ġdisrupted',
 'ĠSpringfield',
 'Ð¸ÑģÑĤ',
 'Ġoven',
 'ĠHof',
 'ĠMyers',
 'Ġdistinguished',
 'ĠSaturday',
 'ĠKennedy',
 'ĠAub',
 'ĠRog',
 '¢',
 'Ġcoming',
 'agonal',
 'Ġdefinitive',
 'Ġabrog',
 'Ġtom',
 'Ġ615',
 'Ġtrimester',
 'ĠPeninsula',
 'Ġdurante',
 'ÂĴ',
 'Ãºn',
 'Ġvolcano',
 'stalk',
 'Ġunb',
 '212',
 '3333',
 'Ġcompact',
 'bus',
 'ĠKosovo',
 'Ġmiscar',
 'Ġcolle',
 'ĠKashmir',
 'Ġreign',
 'Ġtactics',
 'Ġevery',
 'Ø³Øª',
 'Ġbanking',
 'BPF',
 'ql',
 'Ġsugars',
 'Ġexcitement',
 'ĠUnfortunately',
 'coming',
 'ophagy',
 'deficient',
 'ĠVM',
 'Ġpowered',
 'fab',
 'Ġinstinct',
 'Ġridge',
 'uka',
 'Ġpinch',
 'Ġglu',
 'ĠBY',
 'Ġrecording',
 '_(',
 'Ġtxt',
 'Like',
 'Ġpurported',
 'Liu',
 'ĠIndeed',
 'Ġcomme',
 'requently',
 'ĠIP',
 'Lin',
 'ĠGST',
 'orphic',
 'Fin',
 'Ġ"\\',
 'Ġerased',
 'Thomas',
 'reich',
 '407',
 'Ġnvidia',
 'Ġscout',
 'nov',
 'Ġconviction',
 'mark',
 'icial',
 'Ġoverall',
 'ĠTodd',
 'anti',
 'oy',
 'Ġobjectively',
 'Ġtransfers',
 'Ġorbit',
 'igroup',
 'ĠOV',
 'Ġintermittent',
 'Ġcelebrate',
 '-*',
 'Ġpiss',
 'ĠÏĥÏħ',
 'Bill',
 'Ïģ',
 'Ġalloy',
 'Ġadjustable',
 'Î½Î±',
 'Ġexplanation',
 'ĠCompared',
 '337',
 'Ġpriorities',
 'ĠThai',
 'kot',
 'ĠBEL',
 '408',
 'Ġ[\\',
 '(#',
 'Talk',
 'Ġmg',
 'Compare',
 'ĠDOWN',
 'Ġreasonableness',
 'Ġemployers',
 'ĠINCLUDING',
 'im',
 'ogether',
 'ĠHenderson',
 'ĠPf',
 'lb',
 'Ġtechnologies',
 'Ġbiofilm',
 'Ġinstance',
 'unting',
 'wave',
 'verse',
 'ĠJulia',
 '319',
 'ĠHAD',
 'Ġendoscopic',
 'Ġ","',
 'Ġappropriate',
 'ints',
 'Ġfir',
 'Somebody',
 'Ġmechanism',
 'ĠObject',
 'Ġbanana',
 'Ġintu',
 'cases',
 'half',
 'Ab',
 'Ġvalley',
 'Ġprobability',
 'empl',
 'cv',
 'Ġenum',
 'Ġmi',
 'Ġhorizontal',
 'DEFAULT',
 '%%',
 'packed',
 'Fort',
 'Ġ1931',
 'ĠBlind',
 'ameter',
 'ĠApollo',
 'Ġtestify',
 'Ġconvolution',
 'Ġattendant',
 'pinion',
 'edited',
 ')\\].',
 'Ġcpu',
 'ĠLux',
 'picture',
 'Ġconceptual',
 '\\{',
 'ĠYuk',
 ';<',
 'ING',
 'complex',
 'Ġsubd',
 'oscow',
 ']=',
 'Ġgracious',
 'Ron',
 'Ġdepl',
 'Ġ203',
 'Ġprecursors',
 '698',
 'ĠZen',
 'isites',
 'Ġinterpreting',
 'ĠBundle',
 'Ġflange',
 'erve',
 'mania',
 'Ġweighs',
 'ĠShi',
 'ĠVienna',
 'def',
 'pie',
 'armed',
 'fro',
 'Ġaddresses',
 'Ġgeneralized',
 'Ġdisrupt',
 'Ġmunicipal',
 'ĠPlato',
 'Ġgel',
 'Ġretiring',
 'Ġsheath',
 'Ġmerry',
 'Ġassembled',
 'Ġstenosis',
 'atomic',
 'çİ',
 'Äģn',
 'ĠBass',
 'Ġ600',
 'ĠAsset',
 'Ġpatiently',
 'provider',
 'burg',
 'writer',
 'Ġjquery',
 'Ġrefinement',
 'ĠAtlantic',
 'Ġanyway',
 'Ġtournaments',
 'Ġgod',
 'three',
 'Ġrestructuring',
 'Ġdipole',
 'Additionally',
 'Height',
 'rican',
 'Ġmorally',
 'Users',
 'save',
 'connect',
 'Ġseq',
 'Ġthous',
 'Ġspraw',
 'trade',
 'Ġcitrus',
 'Ġsalts',
 'Ġuncor',
 'ĠCzech',
 'åĽ½',
 'ĠAc',
 'sus',
 'Ġinherently',
 'ĠDom',
 'boolean',
 'raged',
 'ensing',
 'ĠCenters',
 'applic',
 'Ð»ÐµÐ½',
 'YES',
 'Ġcommitting',
 'ç¤',
 'ĠWHERE',
 'ĠRoh',
 'è¿',
 'Â·',
 'ĠArabs',
 'ĠABOUT',
 'Ġsocialism',
 'Sem',
 'Ġconnect',
 'ogeneous',
 'Ġtiny',
 'Ġsynerg',
 'essage',
 'mega',
 '16',
 'Ġbelong',
 'ĠAdded',
 'ĠkÃ¤',
 'nk',
 'omers',
 'Winter',
 'apid',
 'Ġstructured',
 'CHA',
 'ĠÅ',
 'isle',
 'Ġmodular',
 'Ġbun',
 'xx',
 'ĠTransfer',
 'Ġgj',
 'ĠCarn',
 'ĠAlexand',
 'Ġastonishing',
 'Ġdialog',
 'Ġsystolic',
 'Ġwebs',
 'Television',
 'Pour',
 'ville',
 'Ð¾Ð²',
 'ĠMutual',
 'ĥ½',
 'Generator',
 'Ġexpired',
 'Ġ1848',
 'Ġgenetics',
 'ĠJJ',
 'Ġoffsets',
 'ĠMiller',
 'ubes',
 'ĠDX',
 'Ġapprove',
 'ivation',
 'circ',
 ']{},',
 'Ġsummoned',
 'Ġplasmid',
 'ITED',
 'Ġchiefs',
 'Ġsupernatant',
 'Ġcalculations',
 '/"',
 'cout',
 'Ġsupposed',
 'Yang',
 'Ġrelegated',
 'anut',
 'Ġinconsistent',
 'profile',
 'infection',
 'ĠOCT',
 'Ġpatriotic',
 'Ġleaked',
 'Ġprojective',
 'ĠSpect',
 'Ġdevast',
 'Ġcreating',
 'dial',
 'Ġinterfaces',
 'Ġvol',
 'Ġfabrics',
 'Ġhydroxyl',
 'ĠLicense',
 'gently',
 'Book',
 'Ġpeek',
 'Ġremaining',
 'chst',
 'Ġmetastasis',
 'Ġcompiler',
 'Data',
 'Ġ(((',
 'ĠCorporation',
 'bank',
 'Ġsubsection',
 'Ġavait',
 'ĠGod',
 'Comments',
 'ĠPhD',
 'ĠDO',
 'Ġrailway',
 'åıĬ',
 'ĠLive',
 'äºĽ',
 'zin',
 'Ġnineteen',
 '}[',
 'Ġpredecess',
 'ãģ¡',
 'Fixed',
 'hours',
 'Ġreluctantly',
 'ĠLCD',
 'ookie',
 'Ġscare',
 'Ġbuild',
 'ĠTou',
 'Einstein',
 'Ġnews',
 'ç«',
 'Ġride',
 'textnormal',
 'Mur',
 'Ġjeopard',
 'Ġparenting',
 'Ġwinning',
 'ĠAuthority',
 '783',
 'Ġprelim',
 'Ġindividuals',
 'Ġtribes',
 'ĠBayesian',
 'Ð·',
 'Anti',
 'ĠFIR',
 'Ġdisciplinary',
 'ohl',
 'Ġarrogant',
 'mid',
 'icorn',
 '0012',
 'atha',
 'Ġpursued',
 'Ġwore',
 'ĠÂµ',
 'ĠAUTHOR',
 'Ġprobation',
 'ben',
 'Ġplease',
 'ĠPalace',
 'ĠPrinciples',
 'ĠCx',
 'Ġfrustration',
 'zero',
 '245',
 'Ġwrapping',
 '779',
 'kernel',
 'IPS',
 'prevent',
 'iorari',
 'ĠAlban',
 'Ġsup',
 'ĠHeaven',
 'Ġwriting',
 'ĠPirates',
 'Ġgrouping',
 'ĠPokemon',
 'âĢĵâĢĵ',
 'otherap',
 'ĠBag',
 'Ġperin',
 'ĠDirectory',
 'Ġextend',
 'zr',
 'fant',
 'Ġphotographic',
 'DAC',
 'president',
 'clamation',
 'electric',
 'ãĥ³ãĥ',
 '187',
 'Ġvil',
 'ĠAmazing',
 'Ġtrips',
 'ĠAddiction',
 'acerb',
 "'(\\",
 'Ġinspected',
 'à©',
 'Ġorganiz',
 'VP',
 'azine',
 'ca',
 'Ġconverge',
 'Ġlaunches',
 'Ġfall',
 'Ġintegrate',
 'infinity',
 'Ġimpulse',
 'èĪ',
 'ĠWit',
 '078',
 'Ġcereb',
 'Ġrevolutionary',
 'Ġcovered',
 'Ġtrack',
 'enu',
 'Ġbarrel',
 'ctl',
 'Ġsequencing',
 '462',
 'ĠQuality',
 'transition',
 'ĠKnights',
 'ĠWhole',
 'ĠConcept',
 'uring',
 'Ġrains',
 'Ġbureaucracy',
 'ents',
 'arden',
 'arcin',
 'Var',
 'emat',
 'Ġau',
 'ĠHL',
 'Ġcontin',
 '1944',
 'æľ',
 'ĠNaCl',
 'ĠSi',
 'ĠRel',
 'phasis',
 'Ġincentives',
 'ĠSams',
 'Ġunited',
 'Ġdeficit',
 'ĠApplying',
 'Ġcircuits',
 'Ġminded',
 'tif',
 '236',
 'anmar',
 'ĠThrough',
 'Ġhero',
 'Ġyielding',
 'ionale',
 'ĠFitzgerald',
 'Ġadam',
 'è´',
 'NS',
 'Ġ488',
 'ury',
 'ĠCab',
 'ĠAnderson',
 'way',
 '382',
 'nio',
 'ĠJR',
 'ĠDarwin',
 'Ġselecting',
 'Ġvisiting',
 'Ġ99',
 'Kay',
 'Ġbrains',
 'BP',
 'Ġlift',
 'Ġgeographical',
 'udson',
 'Ġ97',
 'ĠHepG',
 'ĠKhal',
 'arin',
 'coll',
 'next',
 'Ġneighborhoods',
 'ĠAbu',
 'ĠNP',
 'ĠLt',
 'Ġglucocortic',
 'Ġconcealed',
 'âĶ',
 'ĠDWORD',
 'ĠSDSS',
 'NESS',
 'Ġbarn',
 'apore',
 'Ġcomes',
 'ÐµÑģ',
 'Ġfade',
 '183',
 'urous',
 'Bru',
 'hg',
 'Ġsc',
 'ĠAE',
 'KE',
 'Ġgreens',
 'Ġowed',
 'Ġapparently',
 'ĠLagrangian',
 '277',
 'Ġpers',
 'Ġovernight',
 'Â¯',
 'ĠVALUES',
 'Ġlounge',
 'Ġpregnancies',
 'ĠFri',
 'umines',
 'Ġannouncement',
 'à¸Ī',
 'Ġfibroblast',
 'Ġug',
 'Ġcodec',
 'Ġticks',
 'Ġluck',
 'Content',
 'amples',
 'Ġmelan',
 'Ġworst',
 ':"',
 'anne',
 'INC',
 'ÏīÎ½',
 'ims',
 'ĠBrothers',
 'urities',
 'keV',
 'Ġreduct',
 '699',
 'qr',
 'Ġyoung',
 'Ġballoon',
 'ortex',
 'Ġ12',
 'Ġnour',
 'Ġtattoo',
 'Ġtransitional',
 'orna',
 'shall',
 'Ġminimizing',
 'Ġsorts',
 'orld',
 'aires',
 '})=',
 'Ġsafe',
 'Jason',
 'ymp',
 'Ġmystery',
 'Ġsafely',
 'ĠeconÃ³',
 'Ġcalculator',
 'ĠGordon',
 'Ġinitiatives',
 'Ġremake',
 '________',
 'ena',
 'Ġattend',
 'Medical',
 'ĠLilly',
 'Ġmassage',
 'yellow',
 'RESULTS',
 'Ġprocessed',
 'Ġheadache',
 'ãģªãģı',
 'Î¿Ïį',
 'ĠThermo',
 'PCR',
 'Ġopportunity',
 'Ġfloats',
 '889',
 'Mr',
 'ĠÂ±',
 'gue',
 'ĠBuilt',
 'oxy',
 '458',
 'Ġdischarging',
 'Identity',
 '461',
 'Ġow',
 '^*$,',
 'Dispatch',
 ...]

In [22]:
tokenizer.vocab['teleyadhu']

KeyError: 'teleyadhu'

In [23]:
tokenizer.vocab['kya']

KeyError: 'kya'

In [24]:
tokenizer.vocab['what']

5371

In [25]:
model

ModernBertModel(
  (embeddings): ModernBertEmbeddings(
    (tok_embeddings): Embedding(50368, 768, padding_idx=50283)
    (norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=False)
    (drop): Dropout(p=0.0, inplace=False)
  )
  (layers): ModuleList(
    (0): ModernBertEncoderLayer(
      (attn_norm): Identity()
      (attn): ModernBertAttention(
        (Wqkv): Linear(in_features=768, out_features=2304, bias=False)
        (Wo): Linear(in_features=768, out_features=768, bias=False)
        (out_drop): Identity()
      )
      (mlp_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=False)
      (mlp): ModernBertMLP(
        (Wi): Linear(in_features=768, out_features=2304, bias=False)
        (act): GELUActivation()
        (drop): Dropout(p=0.0, inplace=False)
        (Wo): Linear(in_features=1152, out_features=768, bias=False)
      )
    )
    (1-21): 21 x ModernBertEncoderLayer(
      (attn_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=False)
      (attn): ModernBertAttention(
        (Wqkv): Linear(in_features=768, out_features=2304, bias=False)
        (Wo): Linear(in_features=768, out_features=768, bias=False)
        (out_drop): Identity()
      )
      (mlp_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=False)
      (mlp): ModernBertMLP(
        (Wi): Linear(in_features=768, out_features=2304, bias=False)
        (act): GELUActivation()
        (drop): Dropout(p=0.0, inplace=False)
        (Wo): Linear(in_features=1152, out_features=768, bias=False)
      )
    )
  )
  (final_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=False)
  (rotary_emb): ModernBertRotaryEmbedding()
)

In [26]:
import pandas as pd

data = {
    "text": [
        "Repu NumPy practice chestha.",
        "Help cheyyi CSS.",
        "Main chai pi raha hu.",
        "Best suggestion do JWT ke liye."
    ],
    "label": [0, 1, 0, 1],
    "language": ["te", "te", "hi", "hi"]
}

df = pd.DataFrame(data)

df

                              text  label language
0     Repu NumPy practice chestha.      0       te
1                 Help cheyyi CSS.      1       te
2            Main chai pi raha hu.      0       hi
3  Best suggestion do JWT ke liye.      1       hi

In [27]:
text = "Help cheyyi CSS."
tokens = tokenizer.tokenize(text)

tokens

['Help', 'Ġche', 'yy', 'i', 'ĠCSS', '.']

In [28]:
tokenizer(text)

{'input_ids': [50281, 19576, 1161, 12502, 74, 16710, 15, 50282], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1]}

In [29]:
tokenizer(text, return_tensors="pt")

{'input_ids': tensor([[50281, 19576,  1161, 12502,    74, 16710,    15, 50282]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1]])}

In [30]:
texts = [
    "Help cheyyi CSS.",
    "Best suggestion do JWT ke liye.",
    "Hi"
]

batch = tokenizer(
    texts,
    padding=True
)

batch

{'input_ids': [[50281, 19576, 1161, 12502, 74, 16710, 15, 50282, 50283, 50283, 50283], [50281, 17277, 14876, 513, 500, 16594, 1058, 632, 6683, 15, 50282], [50281, 12764, 50282, 50283, 50283, 50283, 50283, 50283, 50283, 50283, 50283]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]]}

In [31]:
import pandas as pd

df = pd.read_csv("help_intent_dataset_v1_12000.csv")

df.head()

                              text  label language
0     Repu NumPy practice chestha.      0       te
1                 Help cheyyi CSS.      1       te
2            Main chai pi raha hu.      0       hi
3  Best suggestion do JWT ke liye.      1       hi
4            Main chai pi raha hu.      0       hi

In [32]:
df.shape

(12000, 3)

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   text      12000 non-null  str
 1   label     12000 non-null  int64
 2   language  12000 non-null  str
dtypes: int64(1), str(2)
memory usage: 579.5 KB

In [34]:
df["label"].value_counts()

label
0    6000
1    6000
Name: count, dtype: int64

In [35]:
df.isna().sum()

text        0
label       0
language    0
dtype: int64

In [36]:
df.sample(10, random_state=42)

                                    text  label language
1935                   Help karo RAG me.      1       hi
6494           Oka example cheppu Linux.      1       te
1720           Kal API practice karunga.      0       hi
9120               Aaj mausam accha hai.      0       hi
360               Ivala weather bagundi.      0       te
9663        I watched a movie yesterday.      0       en
5277  Suggest the best way to learn LLM.      1       en
8546        Why is this happening in AWS      1       en
2221              Can you solve this bug      1       en
4617           Kal RAG practice karunga.      0       hi

In [37]:
df["language"].value_counts()

language
te    4000
hi    4000
en    4000
Name: count, dtype: int64

In [38]:
pd.crosstab(df["language"], df["label"])

label        0     1
language
en        2000  2000
hi        2000  2000
te        2000  2000

## Preparing the data training and testing/validation

In [40]:
from sklearn.model_selection import train_test_split

train_df, val_df = train_test_split(
    df,
    test_size=0.2,
    random_state=42,
    stratify=df["label"]
)

In [41]:
print("Train:", train_df.shape)
print("Validation:", val_df.shape)

print(train_df["label"].value_counts())
print(val_df["label"].value_counts())

Train: (9600, 3)
Validation: (2400, 3)
label
0    4800
1    4800
Name: count, dtype: int64
label
0    1200
1    1200
Name: count, dtype: int64

In [42]:
train_encodings = tokenizer(
    train_df["text"].tolist(),
    padding=True,
    truncation=True,
    return_tensors="pt"
)

In [43]:
val_encodings = tokenizer(
    val_df["text"].tolist(),
    padding=True,
    truncation=True,
    return_tensors="pt"
)

In [44]:
train_encodings.keys()

KeysView({'input_ids': tensor([[50281,    34,  1432,  ...,    15, 50282, 50283],
        [50281, 13030,  3440,  ..., 50283, 50283, 50283],
        [50281,  6802,    86,  ..., 50283, 50283, 50283],
        ...,
        [50281, 13030,   305,  ..., 50283, 50283, 50283],
        [50281, 14569,   310,  ..., 50283, 50283, 50283],
        [50281, 15061,  3331,  ..., 50283, 50283, 50283]]), 'attention_mask': tensor([[1, 1, 1,  ..., 1, 1, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]])})

In [45]:
print(train_encodings["input_ids"].shape)
print(train_encodings["attention_mask"].shape)

torch.Size([9600, 13])
torch.Size([9600, 13])

In [46]:
import torch

train_labels = torch.tensor(
    train_df["label"].tolist(),
    dtype=torch.long
)

val_labels = torch.tensor(
    val_df["label"].tolist(),
    dtype=torch.long
)

In [47]:
print(train_labels.shape)
print(val_labels.shape)

torch.Size([9600])
torch.Size([2400])

In [48]:
print(train_encodings["input_ids"].shape)
print(train_encodings["attention_mask"].shape)

print(val_encodings["input_ids"].shape)
print(val_encodings["attention_mask"].shape)

print(train_labels.shape)
print(val_labels.shape)

torch.Size([9600, 13])
torch.Size([9600, 13])
torch.Size([2400, 13])
torch.Size([2400, 13])
torch.Size([9600])
torch.Size([2400])

## Data Loader

In [49]:
from torch.utils.data import TensorDataset

train_dataset = TensorDataset(
    train_encodings["input_ids"],
    train_encodings["attention_mask"],
    train_labels
)

val_dataset = TensorDataset(
    val_encodings["input_ids"],
    val_encodings["attention_mask"],
    val_labels
)

In [50]:
train_dataset[0]

(tensor([50281,    34,  1432,   278,   666,   312,   913, 13420,   419,    74,
            15, 50282, 50283]),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]),
 tensor(0))

In [51]:
from torch.utils.data import DataLoader

train_loader = DataLoader(
    train_dataset,
    batch_size=16,
    shuffle=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=16,
    shuffle=False
)

In [53]:
batch = next(iter(train_loader))

print(batch[0].shape) #input sentance
print(batch[1].shape) #attention mask
print(batch[2].shape) # labels

torch.Size([16, 13])
torch.Size([16, 13])
torch.Size([16])

In [54]:
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=2
)

Loading weights:   0%|          | 0/136 [00:00<?, ?it/s]

[transformers] ModernBertForSequenceClassification LOAD REPORT from: answerdotai/ModernBERT-base
Key               | Status     |
------------------+------------+-
decoder.bias      | UNEXPECTED |
classifier.weight | MISSING    |
classifier.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [55]:
sum(p.numel() for p in model.parameters()) # we are about fine tunne this many parameters

149606402

In [56]:
batch = next(iter(train_loader))

input_ids = batch[0]
attention_mask = batch[1]
labels = batch[2]

In [57]:
outputs = model(
    input_ids=input_ids,
    attention_mask=attention_mask
)

In [60]:
print(outputs.logits.shape)
print(outputs.logits[:5])

torch.Size([16, 2])
tensor([[ 0.0752, -0.7237],
        [-0.7493, -0.7712],
        [ 0.1088, -0.5356],
        [ 0.2651,  0.0276],
        [-0.2308, -0.4384]], grad_fn=<SliceBackward0>)

In [61]:
probs = torch.softmax(outputs.logits, dim=1)

print(probs[:5])

tensor([[0.6898, 0.3102],
        [0.5055, 0.4945],
        [0.6557, 0.3443],
        [0.5591, 0.4409],
        [0.5517, 0.4483]], grad_fn=<SliceBackward0>)

In [62]:
probs = torch.softmax(outputs.logits, dim=1)

print(probs[:5])

tensor([[0.6898, 0.3102],
        [0.5055, 0.4945],
        [0.6557, 0.3443],
        [0.5591, 0.4409],
        [0.5517, 0.4483]], grad_fn=<SliceBackward0>)

In [64]:
labels = batch[2]
print("Predicted:", torch.argmax(probs, dim=1))
print("Actual:   ", labels)

Predicted: tensor([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0])
Actual:    tensor([1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0])

In [65]:
loss_fn = torch.nn.CrossEntropyLoss()

loss = loss_fn(
    outputs.logits,
    labels
)

print(loss)

tensor(0.7038, grad_fn=<NllLossBackward0>)

In [66]:
probs = torch.softmax(outputs.logits, dim=1)

print(probs[:5])

tensor([[0.6898, 0.3102],
        [0.5055, 0.4945],
        [0.6557, 0.3443],
        [0.5591, 0.4409],
        [0.5517, 0.4483]], grad_fn=<SliceBackward0>)

In [67]:
loss_fn = torch.nn.CrossEntropyLoss()

loss = loss_fn(outputs.logits, labels)

print(loss)

tensor(0.7038, grad_fn=<NllLossBackward0>)

In [68]:
optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=2e-5
)

In [69]:
old_weight = model.classifier.weight.detach().clone()

In [70]:
model.train()

optimizer.zero_grad()

outputs = model(
    input_ids=input_ids,
    attention_mask=attention_mask
)

loss = loss_fn(outputs.logits, labels)

loss.backward()

optimizer.step()

In [71]:
new_weight = model.classifier.weight.detach().clone()

print(torch.equal(old_weight, new_weight))

False

In [72]:
for batch in train_loader:
    input_ids = batch[0]
    attention_mask = batch[1]
    labels = batch[2]
    
    optimizer.zero_grad()
    outputs = model(
        input_ids=input_ids,
        attention_mask=attention_mask
    )
    loss = loss_fn(outputs.logits, labels)
    
    loss.backward()
    optimizer.step()

In [73]:
model.eval()

ModernBertForSequenceClassification(
  (model): ModernBertModel(
    (embeddings): ModernBertEmbeddings(
      (tok_embeddings): Embedding(50368, 768, padding_idx=50283)
      (norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=False)
      (drop): Dropout(p=0.0, inplace=False)
    )
    (layers): ModuleList(
      (0): ModernBertEncoderLayer(
        (attn_norm): Identity()
        (attn): ModernBertAttention(
          (Wqkv): Linear(in_features=768, out_features=2304, bias=False)
          (Wo): Linear(in_features=768, out_features=768, bias=False)
          (out_drop): Identity()
        )
        (mlp_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=False)
        (mlp): ModernBertMLP(
          (Wi): Linear(in_features=768, out_features=2304, bias=False)
          (act): GELUActivation()
          (drop): Dropout(p=0.0, inplace=False)
          (Wo): Linear(in_features=1152, out_features=768, bias=False)
        )
      )
      (1-21): 21 x ModernBertEncoderLayer(
        (attn_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=False)
        (attn): ModernBertAttention(
          (Wqkv): Linear(in_features=768, out_features=2304, bias=False)
          (Wo): Linear(in_features=768, out_features=768, bias=False)
          (out_drop): Identity()
        )
        (mlp_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=False)
        (mlp): ModernBertMLP(
          (Wi): Linear(in_features=768, out_features=2304, bias=False)
          (act): GELUActivation()
          (drop): Dropout(p=0.0, inplace=False)
          (Wo): Linear(in_features=1152, out_features=768, bias=False)
        )
      )
    )
    (final_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=False)
    (rotary_emb): ModernBertRotaryEmbedding()
  )
  (head): ModernBertPredictionHead(
    (dense): Linear(in_features=768, out_features=768, bias=False)
    (act): GELUActivation()
    (norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=False)
  )
  (drop): Dropout(p=0.0, inplace=False)
  (classifier): Linear(in_features=768, out_features=2, bias=True)
)

In [74]:
correct = 0
total = 0

with torch.no_grad():

    for batch in val_loader:
        input_ids = batch[0]
        attention_mask = batch[1]
        labels = batch[2]

        outputs = model(
            input_ids=input_ids,
            attention_mask=attention_mask
        )

        predictions = torch.argmax(outputs.logits, dim=1)

        correct += (predictions == labels).sum().item()
        total += labels.size(0)

accuracy = correct / total

print("Validation Accuracy:", accuracy)

Validation Accuracy: 1.0

In [75]:

with torch.no_grad():
    for batch in val_loader:
        input_ids = batch[0]
        attention_mask = batch[1]
        labels = batch[2]

        outputs = model(
            input_ids=input_ids,
            attention_mask=attention_mask
        )

        probabilities = torch.softmax(outputs.logits, dim=1)
        predictions = torch.argmax(outputs.logits, dim=1)

        for i in range(5):
            print("Actual:", labels[i].item())
            print("Predicted:", predictions[i].item())
            print("Probabilities:", probabilities[i].tolist())
            print()

        break

Actual: 0
Predicted: 0
Probabilities: [0.9999936819076538, 6.310523076535901e-06]

Actual: 1
Predicted: 1
Probabilities: [1.2249236078787362e-06, 0.9999988079071045]

Actual: 0
Predicted: 0
Probabilities: [0.9999996423721313, 3.5159268918505404e-07]

Actual: 1
Predicted: 1
Probabilities: [8.000540674402146e-07, 0.9999991655349731]

Actual: 0
Predicted: 0
Probabilities: [0.9999992847442627, 6.579271598639025e-07]

In [76]:
texts = [
    "what is webkit",
    "how does webkit work",
    "I'm just reading about webkit",
    "hmm this code looks weird",
    "can you explain this error",
    "I think I understand it now",
    "why is my CSS not working",
    "okay let me try this myself"
]
inputs = tokenizer(
    texts,
    padding=True,
    truncation=True,
    return_tensors="pt"
)
with torch.no_grad():
    outputs = model(
        input_ids=inputs["input_ids"],
        attention_mask=inputs["attention_mask"]
    )

    probabilities = torch.softmax(outputs.logits, dim=1)
    predictions = torch.argmax(outputs.logits, dim=1)

In [77]:
for text, prediction, probability in zip(
    texts,
    predictions,
    probabilities
):
    print("Text:", text)
    print("Prediction:", prediction.item())
    print("P(should respond):", probability[1].item())
    print()

Text: what is webkit
Prediction: 1
P(should respond): 0.9999911785125732

Text: how does webkit work
Prediction: 1
P(should respond): 0.9998194575309753

Text: I'm just reading about webkit
Prediction: 0
P(should respond): 0.3929740786552429

Text: hmm this code looks weird
Prediction: 1
P(should respond): 0.9985803365707397

Text: can you explain this error
Prediction: 1
P(should respond): 0.9999270439147949

Text: I think I understand it now
Prediction: 0
P(should respond): 0.1259189248085022

Text: why is my CSS not working
Prediction: 1
P(should respond): 0.9998100399971008

Text: okay let me try this myself
Prediction: 1
P(should respond): 0.9996047616004944

In [78]:
import os

save_path = "./should_ai_respond_model"

os.makedirs(save_path, exist_ok=True)

model.save_pretrained(save_path)
tokenizer.save_pretrained(save_path)

print("Model saved to:", save_path)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model saved to: ./should_ai_respond_model

In [79]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

loaded_tokenizer = AutoTokenizer.from_pretrained(
    "./should_ai_respond_model"
)

loaded_model = AutoModelForSequenceClassification.from_pretrained(
    "./should_ai_respond_model"
)

loaded_model.eval()

print("Model loaded successfully")

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

Model loaded successfully

In [80]:
text = "what is webkit"

inputs = loaded_tokenizer(
    text,
    return_tensors="pt",
    truncation=True
)

with torch.no_grad():
    outputs = loaded_model(**inputs)

probabilities = torch.softmax(outputs.logits, dim=1)

print("P(do not respond):", probabilities[0, 0].item())
print("P(should respond):", probabilities[0, 1].item())

P(do not respond): 8.85702593222959e-06
P(should respond): 0.9999911785125732

In [81]:
def should_respond(text, threshold=0.80):
    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True
    )

    model.eval()

    with torch.no_grad():
        outputs = model(**inputs)
        probabilities = torch.softmax(outputs.logits, dim=1)

    probability = probabilities[0, 1].item()

    return probability >= threshold, probability

In [82]:
texts = [
    "what is webkit",
    "I'm just reading about webkit",
    "can you explain this error",
    "I think I understand it now",
    "okay let me try this myself"
]

for text in texts:
    respond, probability = should_respond(text)

    print(
        text,
        "=>",
        "RESPOND" if respond else "SILENT",
        f"({probability:.3f})"
    )

what is webkit => RESPOND (1.000)
I'm just reading about webkit => SILENT (0.393)
can you explain this error => RESPOND (1.000)
I think I understand it now => SILENT (0.126)
okay let me try this myself => RESPOND (1.000)

In [85]:
def should_respond(text, eagerness=0.5):
    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True
    )

    model.eval()

    with torch.no_grad():
        outputs = model(**inputs)
        probabilities = torch.softmax(outputs.logits, dim=1)

    probability = probabilities[0, 1].item()

    threshold = 0.95 - (eagerness * 0.50)

    return probability >= threshold, probability, threshold

In [86]:
texts = [
    "what is webkit",
    "I'm just reading about webkit",
    "can you explain this error",
    "I think I understand it now",
    "okay let me try this myself"
]

for text in texts:
    respond, probability, threshold = should_respond(text)

    print(
        text,
        "=>",
        "RESPOND" if respond else "SILENT",
        f"({probability:.3f})",
        f"({threshold:.3f})"
    )

what is webkit => RESPOND (1.000) (0.700)
I'm just reading about webkit => SILENT (0.393) (0.700)
can you explain this error => RESPOND (1.000) (0.700)
I think I understand it now => SILENT (0.126) (0.700)
okay let me try this myself => RESPOND (1.000) (0.700)

In [87]:
should_respond("okay let me try this myself", 0.1)

(True, 0.9996047616004944, 0.8999999999999999)

In [88]:
## Model redyness

In [89]:
import os

model_path = "./should_ai_respond_model"

total_size = 0

for root, dirs, files in os.walk(model_path):
    for file in files:
        filepath = os.path.join(root, file)
        total_size += os.path.getsize(filepath)

print(f"Model size: {total_size / (1024 ** 2):.2f} MB")

Model size: 574.14 MB

In [90]:
total_params = sum(
    p.numel() for p in loaded_model.parameters()
)

trainable_params = sum(
    p.numel()
    for p in loaded_model.parameters()
    if p.requires_grad
)

print(f"Total parameters: {total_params:,}")
print(f"Trainable parameters: {trainable_params:,}")

Total parameters: 149,606,402
Trainable parameters: 149,606,402

149.6M parameter model
        ↓
    benchmark
        ↓
    ONNX export
        ↓
    INT8 quantization
        ↓
   benchmark again
        ↓
 mobile-ready model

In [91]:
import time
import torch

text = "what is webkit"

inputs = loaded_tokenizer(
    text,
    return_tensors="pt",
    truncation=True
)

loaded_model.eval()

start = time.perf_counter()

with torch.no_grad():
    for _ in range(100):
        outputs = loaded_model(**inputs)

end = time.perf_counter()

print("Average inference time:",
      (end - start) / 100 * 1000,
      "ms")

Average inference time: 77.82964773999993 ms

- 149.6M parameters
- 574 MB disk
- 77.8 ms / inference

Current
150M params
574 MB
77.8 ms
       ↓
INT8 quantization
       ↓
much smaller
       ↓
benchmark again
       ↓
mobile decision